import Foundation

public enum WatchOperationKind:String,Hashable,Codable,Sendable{case sessions,composerOptions,transcript,runState,pendingApprovalHead,pendingClarificationHead,tasks,taskRuns,taskRunDetail,skills,skillDetail,skillContent,memoryDocument,insightsAggregate,workspace,filePreview,gitAggregate,diagnostics,media,bots,botConversation,createSession,send,stop,respondApproval,respondClarification,controlTask,sendBot,interruptBot,runStream,botStream}

enum OperationValidationError: Error, Equatable { case invalidLimit, invalidOffset, invalidText }
private func operationText(_ value:String?)throws{if let value{guard !value.allSatisfy(\.isWhitespace),value.utf8.count<=ContractLimits.identifierUTF8Bytes else{throw OperationValidationError.invalidText}}}

public enum WatchReadOperation:Hashable,Codable,Sendable{
 case sessions(scope:ServerScope,collection:SessionCollection,query:String?,localLimit:Int);case composerOptions(scope:ServerScope);case transcript(session:SessionKey,before:Int?,limit:Int);case runState(run:RunKey);case pendingApprovalHead(session:SessionKey);case pendingClarificationHead(session:SessionKey);case tasks(scope:ServerScope,localLimit:Int);case taskRuns(task:TaskKey,page:PageRequest);case taskRunDetail(task:TaskKey,runID:String);case skills(scope:ServerScope,query:String?,localLimit:Int);case skillDetail(skill:SkillKey);case skillContent(skill:SkillKey,fileHandle:PathHandle?);case memoryDocument(scope:ServerScope);case insightsAggregate(scope:ServerScope,days:InsightsDays);case workspace(session:SessionKey,parentPathHandle:PathHandle?);case filePreview(session:SessionKey,pathHandle:PathHandle);case gitAggregate(session:SessionKey);case diagnostics(scope:ServerScope);case media(WatchMediaDescriptor);case bots(scope:ServerScope);case botConversation(bot:BotKey)
 public var kind:WatchOperationKind{switch self{case .sessions:return.sessions;case .composerOptions:return.composerOptions;case .transcript:return.transcript;case .runState:return.runState;case .pendingApprovalHead:return.pendingApprovalHead;case .pendingClarificationHead:return.pendingClarificationHead;case .tasks:return.tasks;case .taskRuns:return.taskRuns;case .taskRunDetail:return.taskRunDetail;case .skills:return.skills;case .skillDetail:return.skillDetail;case .skillContent:return.skillContent;case .memoryDocument:return.memoryDocument;case .insightsAggregate:return.insightsAggregate;case .workspace:return.workspace;case .filePreview:return.filePreview;case .gitAggregate:return.gitAggregate;case .diagnostics:return.diagnostics;case .media:return.media;case .bots:return.bots;case .botConversation:return.botConversation}}
 public var scope:ServerScope{switch self{case .sessions(let s,_,_,_),.composerOptions(let s),.tasks(let s,_),.skills(let s,_,_),.memoryDocument(let s),.insightsAggregate(let s,_),.diagnostics(let s),.bots(let s):return s;case .transcript(let k,_,_),.pendingApprovalHead(let k),.pendingClarificationHead(let k),.workspace(let k,_),.filePreview(let k,_),.gitAggregate(let k):return k.scope;case .runState(let k):return k.session.scope;case .taskRuns(let k,_),.taskRunDetail(let k,_):return k.scope;case .skillDetail(let k),.skillContent(let k,_):return k.scope;case .media(let d):return d.scope;case .botConversation(let k):return k.scope}}
 private func validate()throws{switch self{case .sessions(_,_,let query,let limit):guard(1...100).contains(limit)else{throw OperationValidationError.invalidLimit};try operationText(query);case .transcript(_,let before,let limit):guard(1...50).contains(limit)else{throw OperationValidationError.invalidLimit};if let before,before<0{throw OperationValidationError.invalidOffset};case .tasks(_,let limit):guard(1...64).contains(limit)else{throw OperationValidationError.invalidLimit};case .skills(_,let query,let limit):guard(1...128).contains(limit)else{throw OperationValidationError.invalidLimit};try operationText(query);case .taskRunDetail(_,let runID):try operationText(runID);default:break}}
 public init(from decoder:Decoder)throws{let raw=try WatchReadOperationWire(from:decoder).value;try raw.validate();self=raw}
}

private enum WatchReadOperationWire:Codable{
 case sessions(scope:ServerScope,collection:SessionCollection,query:String?,localLimit:Int);case composerOptions(scope:ServerScope);case transcript(session:SessionKey,before:Int?,limit:Int);case runState(run:RunKey);case pendingApprovalHead(session:SessionKey);case pendingClarificationHead(session:SessionKey);case tasks(scope:ServerScope,localLimit:Int);case taskRuns(task:TaskKey,page:PageRequest);case taskRunDetail(task:TaskKey,runID:String);case skills(scope:ServerScope,query:String?,localLimit:Int);case skillDetail(skill:SkillKey);case skillContent(skill:SkillKey,fileHandle:PathHandle?);case memoryDocument(scope:ServerScope);case insightsAggregate(scope:ServerScope,days:InsightsDays);case workspace(session:SessionKey,parentPathHandle:PathHandle?);case filePreview(session:SessionKey,pathHandle:PathHandle);case gitAggregate(session:SessionKey);case diagnostics(scope:ServerScope);case media(WatchMediaDescriptor);case bots(scope:ServerScope);case botConversation(bot:BotKey)
 var value:WatchReadOperation{switch self{case .sessions(let a,let b,let c,let d):return.sessions(scope:a,collection:b,query:c,localLimit:d);case .composerOptions(let a):return.composerOptions(scope:a);case .transcript(let a,let b,let c):return.transcript(session:a,before:b,limit:c);case .runState(let a):return.runState(run:a);case .pendingApprovalHead(let a):return.pendingApprovalHead(session:a);case .pendingClarificationHead(let a):return.pendingClarificationHead(session:a);case .tasks(let a,let b):return.tasks(scope:a,localLimit:b);case .taskRuns(let a,let b):return.taskRuns(task:a,page:b);case .taskRunDetail(let a,let b):return.taskRunDetail(task:a,runID:b);case .skills(let a,let b,let c):return.skills(scope:a,query:b,localLimit:c);case .skillDetail(let a):return.skillDetail(skill:a);case .skillContent(let a,let b):return.skillContent(skill:a,fileHandle:b);case .memoryDocument(let a):return.memoryDocument(scope:a);case .insightsAggregate(let a,let b):return.insightsAggregate(scope:a,days:b);case .workspace(let a,let b):return.workspace(session:a,parentPathHandle:b);case .filePreview(let a,let b):return.filePreview(session:a,pathHandle:b);case .gitAggregate(let a):return.gitAggregate(session:a);case .diagnostics(let a):return.diagnostics(scope:a);case .media(let a):return.media(a);case .bots(let a):return.bots(scope:a);case .botConversation(let a):return.botConversation(bot:a)}}
}

public enum WatchStreamOperation:Hashable,Codable,Sendable{
 case run(RunKey,afterEventID:String?);case bot(BotKey,replayEpoch:String?,afterSequence:Int?)
 public var kind:WatchOperationKind{switch self{case .run:return.runStream;case .bot:return.botStream}}
 public var scope:ServerScope{switch self{case .run(let k,_):return k.session.scope;case .bot(let k,_,_):return k.scope}}
 private func validate()throws{switch self{case .run(_,let cursor):try operationText(cursor);case .bot(_,let epoch,let sequence):try operationText(epoch);if let sequence,sequence<0{throw OperationValidationError.invalidOffset}}}
 public init(from decoder:Decoder)throws{let raw=try WatchStreamOperationWire(from:decoder).value;try raw.validate();self=raw}
}
private enum WatchStreamOperationWire:Codable{case run(RunKey,afterEventID:String?);case bot(BotKey,replayEpoch:String?,afterSequence:Int?);var value:WatchStreamOperation{switch self{case .run(let a,let b):return.run(a,afterEventID:b);case .bot(let a,let b,let c):return.bot(a,replayEpoch:b,afterSequence:c)}}}
