import Foundation

enum ReceiptValidationError:Error,Equatable{case invalidDate,blankCode,invalidStatus}
private func receiptCode(_ value:String)throws->String{guard !value.allSatisfy(\.isWhitespace),value.utf8.count<=256,value.unicodeScalars.allSatisfy({CharacterSet.alphanumerics.contains($0)||"._-".unicodeScalars.contains($0)}) else{throw ReceiptValidationError.blankCode};return value}
public enum ReceiptPhase:String,Hashable,Codable,Sendable{case dispatching,definitelyNotSent,acknowledged,reconciled,rejected,uncertain}
public struct MutationReceipt:Hashable,Codable,Sendable{public let context:CommandContext;public let operationKind:WatchOperationKind;public let phase:ReceiptPhase;public let updatedAt:Date;public let nonSecretResultID:String?;public init(context:CommandContext,operationKind:WatchOperationKind,phase:ReceiptPhase,updatedAt:Date,nonSecretResultID:String?)throws{guard updatedAt.timeIntervalSinceReferenceDate.isFinite,updatedAt>=context.createdAt else{throw ReceiptValidationError.invalidDate};self.context=context;self.operationKind=operationKind;self.phase=phase;self.updatedAt=updatedAt;self.nonSecretResultID=try nonSecretResultID.map(receiptCode)};private enum CodingKeys:String,CodingKey{case context,operationKind,phase,updatedAt,nonSecretResultID};public init(from decoder:Decoder)throws{let c=try decoder.container(keyedBy:CodingKeys.self);try self.init(context:c.decode(CommandContext.self,forKey:.context),operationKind:c.decode(WatchOperationKind.self,forKey:.operationKind),phase:c.decode(ReceiptPhase.self,forKey:.phase),updatedAt:c.decode(Date.self,forKey:.updatedAt),nonSecretResultID:c.decodeIfPresent(String.self,forKey:.nonSecretResultID))}}
public struct CommandReceipt<Value:Hashable&Codable&Sendable>:Hashable,Codable,Sendable{public let receipt:MutationReceipt;public let value:Value?;public init(receipt:MutationReceipt,value:Value?){self.receipt=receipt;self.value=value}}
public struct EmptyValue:Hashable,Codable,Sendable{public init(){}}
public enum WatchTransportFailure:Hashable,Codable,Sendable{case definitelyNotSent(code:String);case uncertain(code:String);case rejected(status:Int,sanitizedCode:String);case invalidEnvelope(code:String);private func validate()throws{switch self{case .definitelyNotSent(let code),.uncertain(let code),.invalidEnvelope(let code):_=try receiptCode(code);case .rejected(let status,let code):guard(100...599).contains(status)else{throw ReceiptValidationError.invalidStatus};_=try receiptCode(code)}};public init(from decoder:Decoder)throws{let value=try WatchTransportFailureWire(from:decoder).value;try value.validate();self=value}}
private enum WatchTransportFailureWire:Codable{case definitelyNotSent(code:String);case uncertain(code:String);case rejected(status:Int,sanitizedCode:String);case invalidEnvelope(code:String);var value:WatchTransportFailure{switch self{case .definitelyNotSent(let a):return.definitelyNotSent(code:a);case .uncertain(let a):return.uncertain(code:a);case .rejected(let a,let b):return.rejected(status:a,sanitizedCode:b);case .invalidEnvelope(let a):return.invalidEnvelope(code:a)}}}
public protocol WatchReceiptLedger:Sendable{func recordDispatching(context:CommandContext,operationKind:WatchOperationKind)async throws;func transition(id:CommandID,to phase:ReceiptPhase,at:Date,nonSecretResultID:String?)async throws;func receipt(id:CommandID)async throws->MutationReceipt?;func retireSafetyGeneration(_ scope:ServerScope,afterAllCommandsExpiredAt:Date)async throws}
